server:
  port: 8083

spring:
  application:
    name: ai-service

  cloud:
    config:
      enabled: false

  data:
    mongodb:
      uri: mongodb://mongodb:27017/fitnessrecommendation
      database: fitnessrecommendation

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

groq:
  api:
    url: https://api.groq.com/openai/v1/chat/completions
    key: ${GROQ_API_KEY}